apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notenest.fullname" . }}-config
  labels:
    {{- include "notenest.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.global.db.host | quote }}
  DB_PORT: {{ .Values.global.db.port | quote }}
  DB_READ_HOST: {{ .Values.global.db.readHost | quote }}
  DB_READ_PORT: {{ .Values.global.db.readPort | quote }}
  DB_NAME: {{ .Values.global.db.name | quote }}
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  CONSUL_HOST: {{ .Values.global.consul.host | quote }}
  CONSUL_PORT: {{ .Values.global.consul.port | quote }}
  MINIO_ENDPOINT: {{ .Values.global.minio.endpoint | quote }}
  MINIO_EXTERNAL_ENDPOINT: {{ .Values.global.minio.externalEndpoint | quote }}
  MINIO_BUCKET: {{ .Values.global.minio.bucket | quote }}
