apiVersion: v1
kind: Service
metadata:
  name: {{ include "notenest.fullname" . }}-auth
  labels:
    app.kubernetes.io/component: auth-service
    {{- include "notenest.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.auth.port }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.auth.metricsPort }}
      targetPort: metrics
  selector:
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
